version: 2
jobs:

  upload:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Install software
          command: |
            apk update;
            apk add rsync openssh sshpass;
            echo "set ftp:passive-mode true" > ~/.lftprc
      - checkout
      - run:
          name: Upload
          command: |
            mkdir ~/.ssh;
            echo  "upload.bit.nl,213.136.12.217 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIVx+0N0LECcGHPywPCk9uz4/l3kNUVNe5QQRleIkMCTarkYauvRrPNPl49x3LIjF6cZsmQZX7jwgsJqEzfcF98=" > ~/.ssh/known_hosts;
            cd /root/project/;
            sshpass -e rsync -av "--exclude-from=rsync-exclude" --delete . www-divd@upload.bit.nl:htdocs/divd-club;

workflows:
  version: 2
  build_and_upload:
      - upload:
          filters:
            branches:
              only:
                - main
