version: 2
jobs:

  build:
    docker:
      - image: mrseccubus/github-pages:latest
    steps:
      - run: (cd /root/;rm -rf project;mkdir project)
      - checkout
      - run:
          name: Build and check
          command: |
            for site in www.divd.nl csirt.divd.nl; do
              ( 
                echo "*** Building and checking $site ***"; 
                cd $site;
                gem install jekyll-secinfo
                ./update.sh
                jekyll build 2>&1|grep -v 'warning:';
                ./proof_html.sh 
              ) 
            done
      - save_cache:
          key: jekyll-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - "/root/project/www.divd.nl/_site"
            - "/root/project/csirt.divd.nl/_site"
            - "/root/project/.htaccess"


  upload:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Install software
          command: |
            apk update;
            apk add rsync openssh sshpass;
            echo "set ftp:passive-mode true" > ~/.lftprc
      - checkout
      - run:
          name: Upload
          command: |
            mkdir ~/.ssh;
            echo  "upload.bit.nl,213.136.12.217 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIVx+0N0LECcGHPywPCk9uz4/l3kNUVNe5QQRleIkMCTarkYauvRrPNPl49x3LIjF6cZsmQZX7jwgsJqEzfcF98=" > ~/.ssh/known_hosts;
            cd /root/project/;
            sshpass -e rsync -av "--exclude-from=rsync-exclude" --delete . www-divd@upload.bit.nl:htdocs/divd-club;

workflows:
  version: 2
  build_and_upload:
    jobs:
      - build:
          filters:
            branches:
              only:
                - never_ever_run_this
      - upload:
          requires:
            - build
          filters:
            branches:
              only:
                - master
